image: docker:latest
services:
  - docker:dind

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  KUBECONFIG: /etc/deploy/config

stages:
  - build
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  only:
    - tags
  script: mvn clean install
  artifacts:
    paths:
      - target/hello-icp-0.0.1-SNAPSHOT.jar
      
docker-build:
  stage: build
  only:
    - tags
  script:
  - docker build -t $IMAGE_TAG .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker push $IMAGE_TAG

kubernetes-deploy:
  image: dmoutinho/kubectl-gcloud
  stage: deploy
  only:
    - tags
  script:
  - mkdir -p $HOME/.kube
  - echo $K8_GOOGLE_CONFIG | base64 -d > $HOME/.kube/config
  - echo $GOOGLE_KEY | base64 -d > $HOME/.kube/google-key
  - gcloud auth activate-service-account --key-file=$HOME/.kube/google-key
  - kubectl config view  
  - kubectl get all
  - kubectl --record deployment.apps/hello-icp-deployment set image deployment.v1.apps/hello-icp-deployment hello-icp=$IMAGE_TAG image updated
