image: docker:latest
services:
  - docker:dind

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  KUBECONFIG: /etc/deploy/config

stages:
  - build
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: mvn clean install
  artifacts:
    paths:
      - target/hello-icp-0.0.1-SNAPSHOT.jar
      
docker-build:
  stage: build
  script:
  - docker build -t $IMAGE_TAG .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker push $IMAGE_TAG

kubernetes-deploy:
  image: dmoutinho/kubectl
  stage: deploy
  script:
  - mkdir -p $HOME/.kube
  - echo -n $KUBE_CONFIG | base64 -d > $HOME/.kube/config
  - kubectl config view  
  - kubectl config use-context  your-first-cluster-1
  - kubectl --record deployment.apps/hello-icp-deployment set image deployment.v1.apps/hello-icp-deployment hello-icp=$IMAGE_TAG image updated
