image: docker:latest
services:
  - docker:dind

stages:
  - build

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: mvn clean install
  artifacts:
    paths:
      - target/hello-icp-0.0.1-SNAPSHOT.jar
      
docker-build:
  stage: build
  script:
  - docker build -t registry.gitlab.com/dmoutinho/hello-icp .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker push registry.gitlab.com/dmoutinho/hello-icp
