image: docker:latest
services:
  - docker:dind

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

stages:
  - build

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: mvn clean install
  artifacts:
    paths:
      - target/hello-icp-0.0.1-SNAPSHOT.jar
      
docker-build:
  stage: build
  script:
  - docker build -t $IMAGE_TAG .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker push $IMAGE_TAG
