image: docker:latest
services:
  - docker:dind

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  KUBECONFIG: /etc/deploy/config

stages:
  - test
  - build
  - release
  - run

maven-test:
  image: maven:3-jdk-8
  stage: test
  only:
   - tags
  script:
  - mvn test
  - "curl -X POST -H 'Content-type: application/json' --data \"{'text':'$IMAGE_TAG - maven-test success'}\" $SLACK_WEB_HOOK"
  
maven-build:
  image: maven:3-jdk-8
  dependencies:
    - maven-test
  stage: build
  only:
    - tags
  script: mvn clean install -Dtag=$CI_COMMIT_TAG
  artifacts:
    paths:
      - target/hello-icp-0.0.1-SNAPSHOT.jar
      
docker-release:
  stage: release
  dependencies:
    - maven-build
  only:
    - tags
  script:
  - docker build -t $IMAGE_TAG .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker push $IMAGE_TAG
  - docker login -u dmoutinho -p $DOCKER_PASS
  - docker tag $IMAGE_TAG dmoutinho/hello-icp:$CI_COMMIT_TAG-gitlab
  - docker push dmoutinho/hello-icp:$CI_COMMIT_TAG-gitlab

kubernetes-run:
  image: dmoutinho/kubectl-gcloud
  stage: run
  only:
    - tags
  script:
  - mkdir -p $HOME/.kube
  - echo "$K8_GOOGLE_CONFIG" | base64 -d > $HOME/.kube/config
  - export KUBECONFIG=$HOME/.kube/config
  - echo "$GOOGLE_KEY" | base64 -d > $HOME/.kube/google-key
  - /google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=$HOME/.kube/google-key
  - echo $IMAGE_TAG
  - kubectl --record deployment.apps/hello-icp-cmd set image hello-icp-cmd=dmoutinho/hello-icp:$CI_COMMIT_TAG-gitlab
