image: docker

stages:
  - build

build:
  stage: build
  script:
  - export DOCKER_HOST="tcp://localhost:2375"
  - docker build -t registry.gitlab.com/dmoutinho/hello-icp .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker push registry.gitlab.com/dmoutinho/hello-icp
