image: docker:latest
services:
  - docker:dind

stages:
  - build

build:
  stage: build
  script:
  - docker build -t registry.gitlab.com/dmoutinho/hello-icp .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker push registry.gitlab.com/dmoutinho/hello-icp
