apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-icp-deployment
  labels:
    app: hello-icp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-icp
  template:
    metadata:
      labels:
        app: hello-icp
    spec:
      containers:
      - name: hello-icp
        image: dmoutinho/hello-icp:1.0.12.15-gitlab
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: shared-logs
          mountPath: /dev/stdout
      - name: logstash
        image: dmoutinho/logstash
        volumeMounts:
        - name: shared-logs
          mountPath: /usr/share/logstash/mylogs/
        - name: logstash-yml
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
        - name: logstash-conf
          mountPath: /usr/share/logstash/pipeline/logstash.conf
          subPath: logstash.conf
        env:
        - name: NODE_ID
          value: "hello-icp"
        - name: NODE_IP
          valueFrom:
            fieldRef:
             fieldPath: status.podIP
      volumes:
      - name: shared-logs
        emptyDir: {}
      - name: logstash-yml
        configMap:
          name: logstash-yml
      - name: logstash-conf
        configMap:
          name: logstash-conf
